import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import { Providers } from "./providers";
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='dark'>
      <body>
        <Providers>
          <Navbar />
          <div>
            {children}
          </div>
          <Footer />
        </Providers>
      </body>
    </html >
  )
}
